services:
  ai-llm:
    build: !reset null
    image: ai-llm-gemma4:0.26.0-rocr-pollfix-46558b7
    pull_policy: never

  ai-asr-vllm:
    build: !reset null
    image: ai-llm-gemma4:0.26.0-rocr-pollfix-46558b7
    pull_policy: never

  ai-diarize:
    image: ai-diarize:1.0.0-rocr-pollfix-46558b7
    pull_policy: never
