"""
Markdown 리포트 생성기

읽기 쉬운 Markdown 형식으로 테스트 결과를 저장
"""

from pathlib import Path
from datetime import datetime

from ..core.interfaces import IReporter, TestReport


class MarkdownReporter(IReporter):
    """Markdown 형식 리포트 생성기"""

    def __init__(self, output_dir: str = "./quality_test_reports"):
        """
        Args:
            output_dir: 리포트 저장 디렉토리
        """
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def generate_report(self, report: TestReport) -> str:
        """
        Markdown 리포트 생성

        Args:
            report: TestReport 객체

        Returns:
            생성된 리포트 파일 경로
        """
        timestamp = datetime.fromtimestamp(report.timestamp).strftime("%Y%m%d_%H%M%S")
        filename = f"quality_test_{timestamp}.md"
        file_path = self.output_dir / filename

        md_content = self._build_markdown(report)

        with open(file_path, "w", encoding="utf-8") as f:
            f.write(md_content)

        return str(file_path)

    def _build_markdown(self, report: TestReport) -> str:
        """Markdown 문서 생성"""
        timestamp_str = datetime.fromtimestamp(report.timestamp).strftime("%Y-%m-%d %H:%M:%S")

        md = f"""# LLM 채팅 품질 테스트 리포트

**테스트 실행 ID**: `{report.test_run_id}`
**실행 시각**: {timestamp_str}
**테스트된 대화 수**: {report.conversations_tested}

---

## 📊 요약

- **전체 평가 수**: {report.summary['total_evaluations']}
- **통과**: {report.summary['passed']} ✅
- **실패**: {report.summary['failed']} ❌
- **통과율**: {report.summary['pass_rate']:.1f}%

---

## 📈 평가자별 결과

"""

        for evaluator_name, stats in report.summary["by_evaluator"].items():
            md += f"""### {evaluator_name}

- **평균 점수**: {stats['avg_score']:.1f}/100
- **통과율**: {stats['pass_rate']:.1f}%
- **평가 수**: {stats['total']} (통과: {stats['passed']}, 실패: {stats['total'] - stats['passed']})

"""

        md += """---

## 🔍 상세 결과

"""

        # 대화별 그룹화
        by_conversation = {}
        for eval_result in report.evaluations:
            conv_id = eval_result.conversation_id
            if conv_id not in by_conversation:
                by_conversation[conv_id] = []
            by_conversation[conv_id].append(eval_result)

        for conv_id, evals in by_conversation.items():
            md += f"""### 대화 ID: `{conv_id}`

| 평가자 | 점수 | 통과 | 이슈 |
|--------|------|------|------|
"""
            for eval_result in evals:
                status = "✅" if eval_result.passed else "❌"
                issues = ", ".join(eval_result.issues) if eval_result.issues else "-"
                md += f"| {eval_result.evaluator_name} | {eval_result.score:.1f} | {status} | {issues} |\n"

            md += "\n"

        md += """---

## ⚙️ 설정

```json
"""
        import json
        md += json.dumps(report.config, indent=2, ensure_ascii=False)
        md += """
```

---

*Generated by Quality Testing Framework v1.0.0*
"""

        return md
